---
- name: loop test
  hosts: 192.168.0.195
  gather_facts: False
  tasks:
  - name: shell command - /usr/bin/foo
    shell: python3 --version
    register: result
    ignore_errors: True

  - debug:
      var=result
      
  - debug:
      msg: "{{ result.stderr }}"
      when: result is failed

  - debug:
      msg: "{{ result.stdout }}"
      when: result is changed
