---
- name: loop test
  hosts: 192.168.0.195
  gather_facts: False
  tasks:
  - name: shell command - /usr/bin/foo
    shell: /usr/bin/foo
    register: result
    ignore_errors: True

  - debug:
      msg: "{{ result.stderr }}"
    when: result is failed

  - debug:
      msg: "{{ result.stdout }}"
    when: result is changed
