---
- name: ping test
  hosts: target
  gather_facts: True
  tasks:
  - name: ping test
    ping:

- name: touch files test
  hosts: target
  remote_user: ansible
  become: yes
  gather_facts: False
  tasks:
  - name: create directory
    file:
      path: /home/worker/test
      state: directory

  - name: touch file
    file:
      path: /home/worker/test/test.txt
      state: touch

  - name: create file
    #command: "ls -l"
    shell: "ls -l > /home/worker/test/output.txt"
    