---
- name: ping test
  hosts: target
  gather_facts: True
  tasks:
  - name: ping test
    ping:

- name: touch files test
  hosts: target
  remote_user: ansible
  gather_facts: False
  tasks:
  - name: create directory
    file:
      path: /home/ansible/test
      state: directory

  - name: touch file
    file:
      path: /home/ansible/test/test.txt
      state: touch

