---
- name: handler test
  hosts: all
  tasks:
    - name: excute ls
      shell: ls
      notify: 
        - "my handler" 

    - name: status sshd
      shell: systemctl status sshd
      notify:
        - "my handler"

  handlers:
    - name: echo
      debug:
        mag: echo handler message 
      listen: "my handler"

    - name: stop message
      debug:
        msg: stop task
      listen: "my handler"

