---
- name: loop test
  hosts: 192.168.0.195
  gather_facts: False
  tasks:
  - debug:
      msg: "{{ item.user }} - {{ item.group }}"
    loop:
    - user: user1
      group: user1
    - user: user2
      group: group2
