---
- name: web service package install
  hosts: 192.168.0.195
  #gather_facts: True
  tasks:
  - name: Install Apache2 package
    apt:
      upgrade: yes
      update_cache: yes
      name: apache2, php
      state: present
    when: ansible_facts[ "distribution" ] == "Ubuntu"


  - name: Install Httpd package
    yum:
      name: httpd, php
      state: present
    when: ansible_facts[ "distribution" ] == "CentOS"
