---
- name: stat test
  hosts: all
  tasks:
  - name: Get stats of a file
    stat:
      path: /etc/foo.conf
      register: st

  - name: Fail if the file does not belong to 'root'
    ansible.builtin.fail:
    msg: "Whoops! file ownership has changed"
  when: st.stat.pw_name != 'root'
  