---
- name: copy file managed node 1
  hosts: managed1
  remote_user: worker
  become: yes
  tasks:
  - name: copy file with managed1
    copy:
      src: /home/ansible/playbooks/sample.txt
      dest: /home/worker/data/sample.txt

- name: copy file managed node 2
  hosts: managed2
  remote_user: ansible
  become: yes
  tasks:
  - name : copy file with managed2
    copy:
      src: /home/ansible/playbooks/sample.txt
      dest: /home/ansible/data/sample.txt

      